### ISSUE TITLE
Zoom/camera settings per world

### ISSUE THREAD

**Issue by GriffinCodes** [BlueMap-Minecraft/BlueMap#106]
Some of my worlds are pretty large, so I would like to be able to view them from farther out. The current extended zoom setting allows me to zoom out farther, but keeps the rendered area about the same size, leaving a lot of black space on the screen. I also tried modifying the js to allow me to zoom out even farther, but all tiles disappeared at that point.

I would also like to change this setting per world, as world size varies widely and it would be absurd to be able to zoom out on a tiny event world as far as you would zoom out on the main survival world. 

My [BlueMap](https://bluemap.bnn.gg) and [Dynmap](https://map.bnn.gg) for reference

**Comment by TBlueF** [comment]
> but keeps the rendered area about the same size

You can also adjust that with the `lowres render-distance` slider, if you move that all the way up it should slowly load most of the map..

Zooming out even more needs a third map-layer.
Since there already is a ticket and plans to extend the zoom in the future (#3) i will rename this ticket to "Zoom/camera settings per world" and we focus on that in this ticket :)

More customizability for the web-app and maps is definitely a thing i want to add in the future 👍

**Comment by TBlueF** [comment]
Implemented in 3.0
