### ISSUE TITLE
Remove black horizon

### ISSUE THREAD

**Issue by GriffinCodes** [BlueMap-Minecraft/BlueMap#107]
I love seeing the poly terrain in the background of screenshots, but the black horizon is less than appealing; could the sky extend all the way down the terrain?

![image](https://user-images.githubusercontent.com/12417961/96670973-bcafe700-132e-11eb-8d3a-e7294fe9ec8a.png)

**Comment by TBlueF** [comment]
> could the sky extend all the way down the terrain?

It does, the terrain just does not render all the way to the horizon :D

Bluemap looks really weird if you watch if from above, top-down and there is a blue sky, that's why i added the skybox with a black void. If i move the horizon-line down, it gives the (cool but unwanted) impression that the minecraft-world is a sphere.

I will try blending out the black based on the camera-angle, but that might look weird as well, lets see ^^

**Comment by Hafixion** [comment]
+1

**Comment by PieKing1215** [comment]
Would like to see a config option to change the black color (per world preferably)
I have a floating islands world and I feel like it looks better colored instead of black

Current release:
![image](https://user-images.githubusercontent.com/13819558/106865288-f536bf00-6698-11eb-8cf4-bec2cf88faaf.png)
Edited shaders to remove blackness (+ add fading to low res but thats not this issue):
![image](https://user-images.githubusercontent.com/13819558/106969390-b7797b00-6718-11eb-8b46-fe4044cb05cd.png)

**Comment by FrostBird347** [comment]
> If i move the horizon-line down, it gives the (cool but unwanted) impression that the minecraft-world is a sphere.

Is is possible to add a config option to lower this horizon line?

You can manually change the height here: [SkyFragmentShader.js](https://github.com/BlueMap-Minecraft/BlueMapWeb/blob/master/src/skybox/SkyFragmentShader.js)
You can also modify this value directly by searching for `float horizonHeight =` in `/bluemap/web/js/app.cd4bf5d1.js`

**Comment by TBlueF** [comment]
Since the creation of this issue BlueMap's render-distance is now much larger, meaning the horizon is less visible now. Additionally with #268 you will have the option to change the void-color to something else if you want.
For this reason I'll consider this issue solved and will close it.

**Comment by Hafixion** [comment]
I got an email after 3 whole years holy shit
