### ISSUE TITLE
Improve cave-render setting

### ISSUE THREAD

**Issue by TBlueF** [BlueMap-Minecraft/BlueMap#111]
- always render ocean-bottoms (highest solid-opaque block)
- add configurable max-height for caves (render all blocks above that height)

**Comment by kayvanbree** [comment]
My friend is building a base on the ocean floor, and I am building a base in a ravine, so this would be an awesome setting to have. The problem is that 99% of the times you won't need to render that deep.

Some alternatives that would also solve my problem:
- A setting to always render player placed blocks (or chunks/tiles with a certain amount of player placed blocks). This would render a lot of random stuff underground far away from your bases, so this might not be the best solution.
- A setting to always render low sky light level tiles when players spent a certain amount of time in a certain chunk. You could set this to a couple of hours. That way random stuff far from your base won't render.

**Comment by TBlueF** [comment]
@kayvanbree There is 
- no way to figure out "player placed blocks"
- no feasible way to render "around" such a block without completely destroying render-performance *(because we would need to scan a huge amount of blocks for each block we render)*

I might be able to add the second suggestion based on the `inhabited-time`-value of a chunk, no promises tho :)

**Comment by TBlueF** [comment]
implemented with 1.6.1
