### ISSUE TITLE
404 - Not Found

### ISSUE THREAD

**Issue by cyberpwnn** [BlueMap-Minecraft/BlueMap#113]
Doesnt work. Configured properly, Script seems to be loading, all my tiles are rendered, all the files are there, just literally does nothing. 

Spigot 1.16.3, Latest version of bluemap.

Is there a more plug & play solution? Perhaps throw an exception or perhaps log to the console about a misconfiguration?

**Comment by TBlueF** [comment]
Have you checked https://github.com/BlueMap-Minecraft/BlueMap/wiki#q-i-am-getting-404---not-found-when-i-open-the-map and https://github.com/BlueMap-Minecraft/BlueMap/wiki#q-i-still-cant-access-the-website ?

If yes, please consider joining our [discord](https://discord.gg/zmkyJa3) since working with you and finding the issue is much easier there :)
