### ISSUE TITLE
Resource/Mod-Loading Improvements

### ISSUE THREAD

**Issue by pfruh** [BlueMap-Minecraft/BlueMap#129]
**Is your feature request related to a problem? Please describe.**

1. For custom block support, all mods need to be manually added to the `config/bluemap/resourcepacks/` folder.
2. When using a lot of mods as resource packs on a Forge server, starting the server takes **very** long **every time**.

**Describe the solution you'd like**

1. It would be awesome if the plugin could automatically use the installed mods without having to manually copy them to the `config/bluemap/resourcepacks/` folder. This seems to be currently done so only clientside mods are loaded by BlueMap, however to my understanding most (if not all) Forge mods are identical on Client- and Serverside. Mods not containing any assets could just be skipped.
2. To avoid checking all the mods for assets and extracting them every time, the assets could be cached together with metadata (mod name, version and if the mod even has any assets) into a file or folder on first start from where BlueMap could directly load them on future server starts. This cache could then be automatically updated on addition, update or removal of forge mods.

**Comment by TBlueF** [comment]
Improving the mod-loading is planned, the first thing that has to be done here is massively improve the way those mod.jar's are read. There is a massive performance-leak right now with each additional jar that is added. E.g. having only a single file (jar/zip) containing all resources from all mods would already improve the loading-performance massively.
So maybe caching is not needed after fixing this :)

I am unsure about scanning and loading from the mods-folder directly, mostly because it takes the possibility to reorder and remove some of the mods.. E.g. if a mod is freezing/crashing bluemap when it is loaded.
But i think if we add a config-option to disable this and some fail-saves and a watchdog during loading this can be added as well.

*(since it is mod-support this will be a little bit lower-prio for me right now)*

**Comment by TBlueF** [comment]
- [x] Improve/Fix the resource-pack loading performance
- [x] Fail-saves ~~and Watchdog~~ to make loading resources safer and less prone to failure
- [x] Automatically scan the servers mod.jars for resources (with config option to turn this off)
- [x] Also scan the files from fabric.mod.json's "jars" when loading a resource-pack (mod.jar)
- [x] Add option to change how missing-blocks are rendered *(-> will be through resourcepacks)*
- [x] Update the wiki-page about mods!

**Comment by TBlueF** [comment]
Implemented with 2.0
