### ISSUE TITLE
[Question] render files sizes

### ISSUE THREAD

**Issue by alejrobinson** [BlueMap-Minecraft/BlueMap#140]
Is it possible to configure the plugin to render only at normal render quality?

In my server, even compressed, the renders are taking more disk space than the worlds themselves, and given that between high and normal the difference is minimal (as opposed to normal and low, where everything is just blurry), It would be very nice to limit the renders to normal quality, supposing that the disk space gained back is significant.

**Comment by TBlueF** [comment]
Its actually 0. There is no difference on the files between those quality settings: The quality is just the resolution in which your browser renders.. High is super-sampling (to achieve an anti-aliasing effect), normal is native resolution and low is upscaling (rendering on a lower resolution)
The models (files) are the same ^^

Since this is a 3D map, there is not really anything that can be changed in quality or render-speed that would affect the file-size.
(The files are already compressed)

**Comment by alejrobinson** [comment]
ok, thank you very much for the answer, if someday it is possible to optimize and somehow reduce the render file size by some option (even if it lowers the quality), it would be greatly appreciated.

on another note, while looking at the map on the browser my cpu suffers very, very badly, what is the cause for such cpu usage? even when I'am not moving the map and there is no one logged-in (like a static image) this happens

**Comment by TBlueF** [comment]
@alemoh1234 load should be on the gpu, not on the cpu.. make sure you have hardware-acceleration enabled on your browser.

This is not the place for support tho, for support please consider joining our discord, thanks :)

**Comment by alejrobinson** [comment]
both are being loaded, strange, but anyways, thank you again.
