### ISSUE TITLE
Add resource-extensions for all missing tile-entities & special-blocks

### ISSUE THREAD

**Issue by ChloeDawn** [BlueMap-Minecraft/BlueMap#145]
**Is your feature request related to a problem? Please describe.**
Banners are currently invisible due to them being dynamically rendered by the game

**Describe the solution you'd like**
A static model that represents a banner (can easily be made to look identical)

**Comment by TBlueF** [comment]
Adding all the tile-entities that are still missing (banners, shulker-chests, the bell of the bell, mob-/player-heads) is already somewhere on the TODO :)
The bigger problem with banners is the banner-texture, since that is the same issue i mentioned on #146 ^^
That is also planned, but prioritized a little bit lower right now ^^

**Comment by TBlueF** [comment]
Missing resources:
- [ ] banners
- [ ] shulker-chests
- [ ] bell
- [ ] mob/player-heads
- [ ] end-portal/end-gateway
- [ ] hanging-signs
- [ ] cherry-sign
- [ ] decorated pots
- [ ] cake-block (?)

**Comment by ChloeDawn** [comment]
Personally I'd be fine with a blank banner model as a stop-gap to pattern handling. It would be better than no banner imo ^^

**Comment by TyBraniff** [comment]
[Live Examples](https://bluemap.bronzedeathsquad.com/spigot/#flat:-5:-56:13:5:0.48:0.99:0:0:perspective)

Tonight after the kids head off to bed I will finish all heads/skulls and the decorated vases.
With that I think that'll be everything except for the end-portal which I have *no idea* how to do so y'all're on your own for that one
