### ISSUE TITLE
Performance Isuues?

### ISSUE THREAD

**Issue by EsserGaming** [BlueMap-Minecraft/BlueMap#158]
**BlueMap Version:**
*WebServer*

**Description:**
*Bug fix performance suggestion:*
Hi, I looked in the webconsole and saw a whole bunch of 404 errors, maybe you can fix that and that _might_ help with performance. Picture below:
![Screenshot 2021-02-05 130843](https://user-images.githubusercontent.com/36900138/107078005-4e931100-67b3-11eb-86a4-6fc8db302330.png)

**Comment by TBlueF** [comment]
Those 404s are intended, handled perfectly by the web-app .. the browsers are just logging them and there is no way to turn that off. **So this is not a performance issue at all.**

I plan on adding a dummy-response that the webservers can send instead of a 404 to signal a missing/empty tile so it gets rid of that error in the logs because it seems to bug people.

That's not the topic of this issue tho, so i'll just close this :)
