### ISSUE TITLE
Float-Precision issues on extreme distances from 0,0

### ISSUE THREAD

**Issue by WenXin20** [BlueMap-Minecraft/BlueMap#160]
**BlueMap Version:**
`v1.3.1-forge`

I am using:
- [x] mods (on the rendered world)
- [x] resourcepacks (in bluemaps `config/resourcepack` folder)

**Description:**
- Traveling to extreme distances causes map jerkiness and block disconnections. (based on chunks maybe?)

![Capture](https://user-images.githubusercontent.com/12000593/107101350-a134f300-67dc-11eb-9e51-034638c9d9ea.PNG)

**Comment by Toys0125** [comment]
I also have this issue without any mods and using **BlueMap Verison** ``1.3.1-spigot``
![chrome_2021-02-16_13-30-40](https://user-images.githubusercontent.com/15334903/108112124-452f6180-705b-11eb-9363-65476a846f23.png)
PM if you want a link

**Comment by Mark-225** [comment]
Kind of related (and copied from Discord):

Ok so there's two different "symptoms" that start happening at different distances:

- The tiles start "shaking" slightly when rotating or tilting the camera
This starts very early at around 100k but only very slightly. At 200k-300k it is easily noticeable especially when zoomed in. At really high coordinates, tiles start flickering randomly.

- The camera starts "jumping" instead of moving smoothly
Starts at around 500k and gets really bad at around 1m-2m.

(Tested with Firefox on Bluemap Spigot 1.3.1 with a mod that allows for an infinite repeating hires map)

**Comment by DuckyBlender** [comment]
I noticed this too :)

**Comment by Toys0125** [comment]
This is just a guess but I believe that the 3D engine for the WebGL is using floating-point so as we go further out the precision worsens. So my opinion is to use a local cord system based on the current position of the camera or find a BigInt implementation for WebGL.

**Comment by Toys0125** [comment]
Just wanted to show that it still has a similar issue with 1.4.2 at extreme distance. It no longer keeping the blocks uniform.
![chrome_2021-04-19_14-40-20](https://user-images.githubusercontent.com/15334903/115293788-5ceb9a80-a11d-11eb-8a79-151439ac1425.png)
