### ISSUE TITLE
No tile-updates are being detected / scheduled

### ISSUE THREAD

**Issue by xorinzor** [BlueMap-Minecraft/BlueMap#162]
**BlueMap Version: 1.3.1**
*Full version including the target, e.g. `BlueMap-1.3.1-spigot`*
Running on paper 1.16.5-463

I am using:
- [ ] mods (on the rendered world)
- [ ] resourcepacks (in bluemaps `config/resourcepack` folder)
- [ X ] server side plugins

**Description:**
When I mine/place blocks (ie: just cause chunks to update) and then run `/bluemap` it will always say `Scheduled tile-updates: 0`.
Only when forcing a full render using `/bluemap render` it will update the chunks.

The logs don't show any information or errors.

**Comment by DeTOB04** [comment]
I also have this problem on fabric, but newly generated chunks also don't render

**Comment by xorinzor** [comment]
Same as what DeTOB69 says.

Additionally, it seems that when I restart the server, the map is updated instantly without any re-rendering going on.
Does perhaps shutting down, or starting the plugin write some data away to the web files?

I should add that I'm not using the integrated webserver either.

**Comment by TBlueF** [comment]
On discord we have a command for this:

> BlueMap needs to wait until the server saves the world data to disk, so it may take some time for changes to appear on the map.
You can use `/bluemap` and hover over the number of currently scheduled tiles to see more detailed info.
Also make sure to click `clear tile cache` in the menu on the left to make your browser fetch a fresh copy of the updated tiles.

Additionally, bluemap currently does indeed have some reliability issues with automatically updating **sometimes**, there is an issue addressing this: #126 

Usually it should update on its own, if you want detected changes to be rendered instantly you can use `/bluemap debug flush` .. if something doesn't update even after that or a server-restart then that's due to the reliability issue and until that is fixed you'll need to manually update it using a radius render `/bluemap render <radius in blocks>` :)

Closing this in favor of #126

**Comment by xorinzor** [comment]
I had cleared the tile cache, and had the chrome developer tools open to disable my local cache too. It doesn't seem to be a client-side caching issue. The fact that the map is updated when the server restarts supports this theory, indicating that the plugin isn't handling some sort of event / file write correctly.

I force my minecraft server to write data to the disk every 15 minutes before running my incremental backup too.

I'll see if the debug command works for me and force that occasionally.

**Comment by TBlueF** [comment]
#126 will completely change the way map-updates are handled. Which makes any bugfixes on the current map-update system obsolete. So, since i have limited time and resources here, I'd prefer to just wait out #126. It is scheduled to be worked on directly after the web-app rewrite is done, which i am working on rn :)

**Comment by xorinzor** [comment]
Yea I commented a bit too quickly ;)
Re-reading your initial answer and the referenced issue I realized it's fine

If the flush command forces it to render changed chunks that's a decent workaround for the time being (and else they'll just have to make due with a forced re-render every 24 hours for now).

I'll keep an eye on the repo! :)

**Comment by xorinzor** [comment]
Just as an update, `/bluemap debug flush` combined with a "clear tile cache" does indeed work :)
I just created a cronjob which runs the command every minute, and that should work :)

That said, it seems it only detects changes by players.
A tree growing didn't update the map (even after flushing) until I placed/broke a block and flushed again

**Comment by TBlueF** [comment]
note that this command saves your world similar to `/save-all flush` .. so you might get lagspikes when executing it every minute ^^

**Comment by xorinzor** [comment]
Hm, didn't notice any of that yet, but good to know ;)
