### ISSUE TITLE
Black map

### ISSUE THREAD

**Issue by Dreaming-Codes** [BlueMap-Minecraft/BlueMap#168]
Bluemap behind nginx is completely black.
https://map.casarizzotti.com/

**Comment by Dreaming-Codes** [comment]
![image](https://user-images.githubusercontent.com/10401566/109390607-fd3df380-7912-11eb-8642-a6bfd08c78bd.png)
The problem doesn't seem to be nginx

**Comment by Dreaming-Codes** [comment]
i'm using spongeforge with nucleus and luckperms in 1.12.2

**Comment by TBlueF** [comment]
Hey @Dreaming-Codes, 
to make NGINX work with bluemap there is a special setup needed: https://github.com/BlueMap-Minecraft/BlueMap/wiki/Directly-hosting-BlueMap-with-external-webservers
Have you done that already?

**Comment by Dreaming-Codes** [comment]
> Hey @Dreaming-Codes,
> to make NGINX work with bluemap there is a special setup needed: https://github.com/BlueMap-Minecraft/BlueMap/wiki/Directly-hosting-BlueMap-with-external-webservers
> Have you done that already?

Yes, but nothing seems to change. However it doesn't work also with a localhost curl

**Comment by Dreaming-Codes** [comment]
Also the mod integrated web server doesn't work http://79.26.125.149:8100/

**Comment by TBlueF** [comment]
This is probably a different issue then, we have an FAQ with that exact problem: https://github.com/BlueMap-Minecraft/BlueMap/wiki#q-i-have-a-black-map--a-lot-of-the-map-is-missing

Since this is not a bug or feature/request i'll close this for now :)

**If you need more support with setting up BlueMap, please consider joining our discord!**
