### ISSUE TITLE
Cache models

### ISSUE THREAD

**Issue by Katrix** [BlueMap-Minecraft/BlueMap#17]
Currently all models are always redownloaded each time they are needed. Would be great if the webserver could supply some information like ETags and configure some simple caching around it. That way the browser could use an old copy it already downloaded if the ETag matches.

**Comment by TBlueF** [comment]
So, i think i can add generating ETags and comparing them. Also there might be some improvement by setting and handling `Cache-Control` headers.

However i have tested on Chrome and Firefox (Stable and Nightly) and all browsers cached the models after one download and didn't even ask the server.

Also there already is the `Last-Modified` header being sent and the `If-Modified-Since` header being handled by the webserver.
