### ISSUE TITLE
Make a guide or feature to using cli to render map offsite

### ISSUE THREAD

**Issue by Toys0125** [BlueMap-Minecraft/BlueMap#177]
The main issue I have is that my Minecraft server is running on a quad-core CPU and it doesn't have the power to render the map while people are currently playing on it. I want the ability to use the CLI on a separate server to render tiles either live or in an hourly-based approach.

**Describe the solution you'd like**
So currently i have the ``rmstate`` that tells what tiles that need to be updated and I tried using that with the CLI to update the map, either when the new system comes i won't have to use the ``rmstate`` or have bluemap auto-detect when a ``rmstate.update`` has been placed that removes the updated titles in the ``rmstate`` so when I pull from the current it would be new tiles.

My current process is using Rsync to pull the world files, then the ``rmstate`` after every restart. Than I delete the rmstate so it starts new. After the rending, I sync the updated map back to the server.

**Comment by TBlueF** [comment]
That's already possible,
You don't need to do anything with the rmstate to make the cli update the map:

Just rsync the world-files and then start a cli-render..
Without the `-f` flag, bluemapcli will only render chunks that have been changed since the last render.
(Each chunk has a "modified" timestamp, and when the cli finishes a render it saves a timestamp to the `bluemap/web/data/settings.json`)

If you start a render every hour you will see the cli will update all chunks that are changed, and nothing more :)
Just make sure the render finishes, or else it will try to resume the old render.

If you need support with that, consider joining our discord or reddit :)

**Comment by Toys0125** [comment]
Well is it possible to then disable the tracking and render queue on the bluemap plugin but leave the webserver on?

**Comment by TBlueF** [comment]
Planned: #126
