### ISSUE TITLE
Location issue

### ISSUE THREAD

**Issue by EsserGaming** [BlueMap-Minecraft/BlueMap#192]
**BlueMap Version:**
1.5.1

**Description:**
https://esser.fun/files/2021-05-17%2016-33-11.mp4

**Comment by TBlueF** [comment]
Nice video, but what's the bug, and
how would you expect it to behave instead?

**Comment by EsserGaming** [comment]
The video shows what happens, but isn't it supposed to switch to 0 instead of blank?

**Comment by TBlueF** [comment]
If you type in nothing you get nothing, makes sense to me

**Comment by TBlueF** [comment]
Okay:
Just to be fully clear here.. 

I think i know what you mean, and i agree that it would be a (small) improvement to make sure an empty coordinate-input field does not result in a black-map and a warning in the console. I'll add that to the TODO 👍 

What was bothering me was the lack of information on this issue, i basically had to "guess" what you wanted to say.
That might be my fault though, since i have not put clear instructions what i would consider a "good issue" anywhere..
I'll add that info now :)

**Comment by EsserGaming** [comment]
Apologies, I am not a man of words. I don’t know why I just can’t explain issues like that well.
