### ISSUE TITLE
A proxy version of the plugin

### ISSUE THREAD

**Issue by DreiMu** [BlueMap-Minecraft/BlueMap#235]
**Is your feature request related to a problem? Please describe.**
I would like to have a mapoverview for many servers in a network (velocity) on one site

**Describe the solution you'd like**
Another plugin that gives you the possibility to have bluemap on multiple servers and this plugin takes all the maps and puts them in a new settings file and redirects the requests for data to the plugins on the server (i have no idea if this would work with texturepacks but if you just create a settings.json with all the settings and send it to the client it *should* work...)

**Comment by TBlueF** [comment]
Once #138 is done, this will be possible using a normal nginx-proxy.
A multi-server environment is definitely an advanced server-setup so the ability to setup and use NGINX (or similar) for this can be expected imo :)

Because of this, I'll close this issue (while referring to #138), since a separate plugin just as a proxy is not needed.
