### ISSUE TITLE
Export to .blend

### ISSUE THREAD

**Issue by AstroOrbis** [BlueMap-Minecraft/BlueMap#239]
I think that it would be very useful to be able to export regions to a .blend file.
Maybe rendering every block would work, or making a huge poly out of the region?

**Comment by TBlueF** [comment]
The map-tiles are already "poly meshes", saved as a gzip compressed json in this format: https://threejs.org/docs/index.html?q=buff#api/en/core/BufferGeometry
Converting them into .obj files should be easy if you have some JS knowledge and read into ThreeJS. Maybe there are even tools already for this.
And blender can import .obj files :)

BlueMap will not get a built-in exporter to different files, since this is way out of scope for a mapping tool ^^

**Comment by AstroOrbis** [comment]
Allright, thank you so much!

I'm just a blender noob :3

**Comment by crazygmr101** [comment]
[This](https://theduckcow.com/dev/blender/mcprep/) addon, and [this](https://www.youtube.com/watch?v=iRixJzraHFI&t=26s) video should do the trick.

**Comment by AstroOrbis** [comment]
Tysm!
