### ISSUE TITLE
Failed to render tile

### ISSUE THREAD

**Issue by poqdavid** [BlueMap-Minecraft/BlueMap#24]
After a server crash noticed this error on our logs it's not spammed or anything just submitting error
https://paste.ee/p/gdfsQ
tho this didn't cause the server crash

**Comment by TBlueF** [comment]
I noticed that as well, i believe that error occurs if buemap is parsing a region-File in the same moment that minecraft is writing changes to it.
It is not really harmfull, it only causes one tile to not being rendered.
Since i don't have an idea how to prevent this, that error needs to be catched and the affected tile rescheduled for a second try..

**Comment by poqdavid** [comment]
Oh ok cool

**Comment by TBlueF** [comment]
Should be fixed now, reopen please if this error persists with the latest version :)

**Comment by TBlueF** [comment]
Still happening on some occasions.
Maybe try to implement reschedules with a longer wait-time or even for server restart. And if all reschedules don't work, just drop the tickets without error.
