### ISSUE TITLE
Limit transfered Data-Volume by limiting the renderdistance in webserver.conf or render.conf

### ISSUE THREAD

**Issue by wolfkarst** [BlueMap-Minecraft/BlueMap#248]
**Is your feature request related to a problem? Please describe.**
Loading a Map of e.g. 15000x15000 Blocks needs at my server about 4,8 GB data-volume (Compression is enabled), which adds up to several TB if the Map gets used frequently by the players. The data-volume can be significantly reduced by limiting the render distance for Lowres from 10000 to 2500 and for Highres from 500 to 120. But not all players are doing this voluntary. This also applies for a preset and maximum of the flightheight, as for a Height, where the Lowres-Rendering is switched off, because it's useless.

**Describe the solution you'd like**
Add either in webserver.conf for all worlds or in render.conf a setting where the Server-owner can limit the maximum and the presetted render-distances:
renderHiresInitial: 125
renderHiresMax: 250
renderLowresInitial: 1000
renderLowresMax: 2500
renderLowresHeight: 1000
FlightHeightInitial: 1000
FlightHeightMax: 2500

![image](https://user-images.githubusercontent.com/1564914/135985990-d5372c37-6913-4495-a0c6-dbe25963b26c.png)
![image](https://user-images.githubusercontent.com/1564914/135986868-afa2e92c-3bb0-4e68-833a-51f138b86854.png)

**Comment by TBlueF** [comment]
Actually i think, you are looking at the wrong values..
In the second screenshot of yours it says `4503 MB Ressourcen` .. which i guess is where you are getting your 4,8 GB value from ..
However that is the decompressed size of the resources! The actual transferred size is to the left of that: `299 MB übertragen` which is significantly less :)

**Comment by wolfkarst** [comment]
Doesn't matter, after i have installed the bluemap on my Server, the Data-volume of the Web-transfer by 8 Players raised over 1TB during 9-10days (Which created an Alert)... 
The only Web-Service is the Bluemap on the Server, and 8 Players (say 4 active Players and 4 Players with only 50%) keep reloading only 10 Times a day = 6 Players x 10 Times x 300 MB x 10 Days will be 180 GB or round about 540GB per Month.
I know when something is new, the players a trying several things and are doing a lot of reloads and a total value of 300-500GB will be a long-term realistic goal, but if you have a limited data-transfer on the Server, every GB is counting.
If not every Server-Admin is using it, set the defaults to the current values, but please make other Server-Admins able to limit the size. Thanks.

**Comment by wolfkarst** [comment]
Don't get me wrong, Bluemap is visual much better than dynmap and the used space on the Server is by factor 15-20 much less, but the transferred data volume is also an criteria for small servers.

**Comment by TBlueF** [comment]
Not getting you wrong, all fine :)

I just added a new issue #249 with a change that i want to do, but never created an issue for it.
That change also includes some of the config-additions that you are suggesting :)

It does not include *"a Height, where the Lowres-Rendering is switched off"* because that just doesn't make sense.
Did you mean the hires-layer? The one you see when you are zoomed-in?

Also it will take a while until i get to implementing issue #249 (check the [TODO](https://github.com/BlueMap-Minecraft/BlueMap/projects/1?fullscreen=true)).. 
So until then you might want to look into cloning the `BlueMapVue` repo changing the values there and building your own version of the webapp :)
The min-max values can be changed here: https://github.com/BlueMap-Minecraft/BlueMapVue/blob/master/src/components/Menu/SettingsMenu.vue#L24-L27
And the default values here: https://github.com/BlueMap-Minecraft/BlueMapWeb/blob/3618113c22174d2ce7d2eb69add3404111811bc3/src/MapViewer.js#L72-L73
*(BlueMapWeb is included in BlueMapVue)*

**Comment by wolfkarst** [comment]
```
It does not include "a Height, where the Lowres-Rendering is switched off" because that just doesn't make sense.
Did you mean the hires-layer? The one you see when you are zoomed-in?
```
Sorry, my fault ... yes, i meant the HiRes-Switch-Off, which currently is happening at about 2000.

**Comment by TBlueF** [comment]
The hires switch-off is a little difficult to "just change", because its closely aligned to some controls and camera-settings. e.g. the cameras ["far-plane"](https://de.wikipedia.org/wiki/Clippingebene) .. 
It is not useless tho: 
Switching off the hires, improves fps by a lot when zoomed out, improving the useabillity.
However it doesn't reduce the transferred data, so making it switch off earlier would not really do anything ^^

I will see if changing it is feasible and if it is, i will include it in the same issue as the other settings :)

**Comment by wolfkarst** [comment]
thanks a lot for you afford

**Comment by TBlueF** [comment]
I'll close this in favour of the other issue then :)
