### ISSUE TITLE
Feature request: Creating markers using signs (+ making icons more accessible)

### ISSUE THREAD

**Issue by ThatIcyPolarBear** [BlueMap-Minecraft/BlueMap#280]
**Is your feature request related to a problem? Please describe.**
At the moment most of my players don't know how to make a marker on the map and then I have to do it. It is also not very easy to give that marker an icon. As far as I know, only someone with access to the hosts machine can give a marker a custom icon.

**Describe the solution you'd like**
It would be nice if players could create markers using a sign, for example what could be written on the sign:
-marker-
<marker name>
<icon>
There could also be another line with the marker id.
-marker- would be an indicator to the plugin that this sign is met to be a marker on the map.
<marker name> would be the display name of the marker, maybe it could also be the marker id.
<icon> would refer to an icon placed in an icon folder somewhere in the bluemap config folder. Maybe there could already be some presets in there. It would be nice if the server owner could add his own icons for example house.jpg and if the player wrote house on the <icon> line then that icon would appear on the map.
This icon part could also be added to the command because as of now you can't choose an icon in the command line.

The marker would ofcourse appear on the location of the sign an it would be removerd if the sign was destroyed.

This is all just an idea and you may ofcourse change some bits but i think it would be nice if this feature were added.

EDIT: one last final thought:
It would also be nice if the creating of markers using signs had a permission wich you could give to players using any permissions plugin. Maybe add in the bluemap config if default players could automatically do it or if they need the permission.

**Comment by pop4959** [comment]
This is probably something that would best be done in a 3rd party BlueMap addon (not directly in the plugin itself) using the API

**Comment by TBlueF** [comment]
BlueMap is moving away from providing player/ingame-oriented tools for marker-management itself. This is because most of such tools heavily rely on the underlying plugin-API (spigot/fabric/forge/sponge). Currently, most of bluemap's code is independent of those API's and the goal is to keep it that way.

*Does that mean there will be no way to use signs to create bluemap-markers?*
No! There is a way:

BlueMap has already a full marker-API for other plugins to integrate with. So it's totally possible to make an extension-plugin that does exactly what you described :)
In fact, someone already started making such a plugin: <https://github.com/theAspenGrove/BlueMap-Signs>
*(According to the Author it works already, but isn't finished yet.)*

**Comment by mmuziek** [comment]
Great idea btw gonna add this to MCGBME for those who like it :)
