### ISSUE TITLE
Macaw's Bridges Block not showing despite seemingly correct BlockModels

### ISSUE THREAD

**Issue by WenXin20** [BlueMap-Minecraft/BlueMap#294]
### What i did / Steps to reproduce

1. Install Bluemap, Terraqueous, & Macaw's Bridges
2. Add mods to resourcepacks folder

### Expected result

- Blocks either should render or render invisible like some modded chests

### Actual result

- The blocks provide xray into the world below, leaving ugly holes

### Context
**BlueMap Version:**  
`1.7.2-forge-1.18.1`
- [Terraqueous](https://www.curseforge.com/minecraft/mc-mods/terraqueous)
-  [Macaw's Bridges](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)

Terraqueous Fallen Branch:
![image](https://user-images.githubusercontent.com/12000593/155896105-b9e8239f-fa79-409f-92c4-5f5ad3af9886.png)

Macaw's Bridges Bridge Stair:
![image](https://user-images.githubusercontent.com/12000593/155896158-f34e9be3-0928-49bc-9ab1-136096d06979.png)
(Railings in the normal flat bridge also doesn't render.)

**Comment by TBlueF** [comment]
Terraqueous uses `.obj` blockmodels from forge which are not supported by bluemap. BlueMap tries to render them and fails, which is why it is rendered that way. Adding support for `.obj` blockmodels is and will **not** be planned right now.

Idk what's wrong with Macaw's Bridges .. seems like they are using a normal multipart blockstate which should work. This would need more testing.

**Comment by WenXin20** [comment]
I don't mind if .obj models are not supported. I'm just curios if there is a way to prevent the xraying when .obj models are loaded in the map. Thanks for looking into this!

**Comment by TBlueF** [comment]
@WenXin20 You can remove the mod from bluemaps resourcepack-folder, **or** - to only remove the broken ones - remove all broken blockstates from the mod-jar (that you placed inside bluemaps resourcepack folder) ..

If you need help with this, please ask in our [discord](https://discord.gg/zmkyJa3) since GitHub is not meant for support :)

**Comment by WenXin20** [comment]
Originally I didn't have the mod in the resources folder, and the x-raying blocks instead displayed as missing textured blocks

**Comment by TBlueF** [comment]
![image](https://user-images.githubusercontent.com/10765470/189523075-c23e4955-8b28-428c-ada0-5d09c0292452.png)
Marcaw's Bridges seem to be working in 3.3. 
Probably fixed itself by the resource-parsing rewrite :)
