### ISSUE TITLE
Support for itemsadder custom blocks

### ISSUE THREAD

**Issue by The-Nyla** [BlueMap-Minecraft/BlueMap#297]
**Is your feature request related to a problem? Please describe.**
Any custom blocks added by itemsadder show up as noteblocks

**Describe the solution you'd like**
support for itemsadder resource packs, the idea is that bluemap will read the resource pack and give custom Itemsadder blocks the correct texture

**Comment by TBlueF** [comment]
Usually it should be enough to add the resource-pack to bluemaps resourcepacks-folder. If you have not tried that already, then try it, it might just work: https://bluemap.bluecolored.de/wiki/customization/ResourcePacks.html

If it doesn't work: I don't know how itemsadder works exactly and if they are doing something special with their resourcepacks .. but i can't check that because itemsadder is a paid resource. So to evaluate if this is feasible I would at least need an example resource-pack from that plugin to look at.

Closing this for now, if the first doesn't work and you can provide an example resource-pack, feel free to reopen.

**Comment by The-Nyla** [comment]
Yep, it doesn't work currently. I'll now provide a pack and a basic explanation on how the custom blocks work:

The blocks work because noteblocks have nearly 800 states depending on their note and instrument, so itemsadder reserves about 25-ish states for vanilla noteblocks to work, and can give all the other states their own texture.

pack:
[pack.zip](https://github.com/BlueMap-Minecraft/BlueMap/files/8208369/pack.zip)

**Comment by TBlueF** [comment]
@BookWyrm114 

Placed a noteblock with `instrument: basedrum` and `note: 0` ... installed your resourcepack on bluemap ... got expected result: Block rendered as a ruby block ^^

So it seems to work for me. Make sure you re-render your map and use the `Update Map` button on the web, after you installed the resource-pack.

Some images:
![image](https://user-images.githubusercontent.com/10765470/157295412-a57fadad-6a18-423f-8090-b0b89070d329.png)
![image](https://user-images.githubusercontent.com/10765470/157295458-adbfd533-e113-43fd-9397-156019b208cb.png)

:)

**Comment by The-Nyla** [comment]
Hmmm, I reloaded bluemap and updated the map,  but I’m restarting my server now, if that doesn’t work I’ll re-render everything, thanks!
