### ISSUE TITLE
Ability to disable full render upon startup

### ISSUE THREAD

**Issue by ghost** [BlueMap-Minecraft/BlueMap#298]
**Is your feature request related to a problem? Please describe.**
Yes, I do not like how a full render is triggered upon startup.

**Describe the solution you'd like**
An option to disable full render on server startup.

**Comment by TBlueF** [comment]
BlueMap doesn't do a "full-render" on startup. It just updates the map. Which means it only renders chunks that have changed and need to be updated. The same thing that it also does all the time to keep it updated. 

The reason you see lots of render-activity on startup, is because minecraft saved a lot of chunks to the disk when the server was stopped.. And all those chunks need to be updated.

If you don't want a map to update you can use `/bluemap freeze <map>`.
