### ISSUE TITLE
"Full view" and in game marker creation

### ISSUE THREAD

**Issue by paj1s** [BlueMap-Minecraft/BlueMap#299]
Firstly i must say that this plugin is ingenious, i was solving some minor problems with my dynmap and somehow came across this and was so astonished i immediately installed this and removed dynmap :D 

The plugin is great but still im little sad it cannot display the whole map as dynmap could. I know that for the 3d view it needs some extra resources but im thinking of somekind of bird view like in dynmap so the whole map is visible in hires.

The next thing is markers and regions, i don't know if it's already a thing but i didn't find it. It would be great if players with permission could create regions and markers themselves using command or tool which would be configurable.  (golden hoe for example) .

The last thing i want to ask came to my mind while writting this, circa how much does one person watching the map consume of internet bandwidth? I hope i formulated that question understandable. It's just i didn't even thought of that it also needs a beefy internet connection and i have only 20MB/s upload :D

**Comment by paj1s** [comment]
Oh there is a slider in the menu, that makes life a lot easier.

**Comment by TBlueF** [comment]
> The plugin is great but still im little sad it cannot display the whole map as dynmap could. I know that for the 3d view it needs some extra resources but im thinking of somekind of bird view like in dynmap so the whole map is visible in hires.

Extending the map view is on the [TODO](https://github.com/BlueMap-Minecraft/BlueMap/projects/1?fullscreen=true). I really want this improved as well! But there is a lot on the TODO before it and its a big topic, so currently i just hope i will get there some day. ^^'

> The next thing is markers and regions, i don't know if it's already a thing but i didn't find it. It would be great if players with permission could create regions and markers themselves using command or tool which would be configurable. (golden hoe for example) .

Markers are generally a topic for 3rd-party addons using BlueMaps API. Yes, the API needs to be extended and generally some work, but its already possible to create powerful markers with it :) 
Somehow no one has really made an addon yet that adds good marker-commands in general, but that would be totally possible :) 
Here is more explanation why i don't want to add marker-commands to BlueMap itself: https://github.com/BlueMap-Minecraft/BlueMap/issues/211#issuecomment-879784008

> The last thing i want to ask came to my mind while writting this, circa how much does one person watching the map consume of internet bandwidth? I hope i formulated that question understandable. It's just i didn't even thought of that it also needs a beefy internet connection and i have only 20MB/s upload :D

BlueMap sends map-tiles as 3d-models. It tries to optimize them as much as possible (culling away faces that cant be seen, gzip compressing everything). But they are still using up quite some space. The actual size depends on lots of factors like map-complexity. Also the browser caches map-tiles as well.
How much **bandwidth** one user takes is not something you can generally answer .. A user takes as much bandwidth as they can, but then for a shorter time because the map-tiles download faster :D
The more bandwidth you and the user can use, the faster their map loads .. if there are multiple users then they'll split your bandwidth .. (very simplified) .. ^^

**One last thing:**
Please don't use GitHub issues for questions and (brief/unrefined) suggestions, we have a [Discord](https://discord.gg/zmkyJa3) (or a [Reddit](https://www.reddit.com/r/BlueMap/) that i need to visit more often) that are suited way better for that :)
