### ISSUE TITLE
[Suggestion] Nova compatibility

### ISSUE THREAD

**Issue by The-Nyla** [BlueMap-Minecraft/BlueMap#303]
**Is your feature request related to a problem? Please describe.**
Nova uses entities for custom blocks and machines, so currently a nova quarry on bluemap looks like this:
![image](https://user-images.githubusercontent.com/79489385/169074165-16b1190a-1367-48e0-af54-cad4ae2b0e80.png)
Most of the quarry is invisible and the block that are there are just normal blocks

**Describe the solution you'd like**
Support for Nova machines and blocks to be rendered correctly on bluemap. it would probably require hooking into nova somehow and registering nova's blocks as actual custom blocks on bluemap's end, since it can't be done with just a resource pack due to nova using armor stands.

**Comment by Chicken** [comment]
BlueMap won't add support for any mods. The mods will have to add support for BlueMap. But consider this is about entities I personally think it will not happen.

edit: Oh well, it's actually a plugin. Support just for nova won't happen anyway. Armorstand (and other entities) rendering might happen in the future.

**Comment by The-Nyla** [comment]
ok, thanks! however when that's added it would be nice to be able to hook into plugins and only render specific armorstands/entities due to plugins like modelengine, which would fill the map with frozen custom entities.

**Comment by TBlueF** [comment]
BlueMap can be configured to render any **Block** as long as it has the correct resources for that block. If Nova uses reskinned block to display their machines, then it would be possible to make a resourcepack that can be loaded with bluemap and would enable bluemap to render nova-machines properly ... **Entities** are generally not rendered by bluemap right now.
The abillity to render entities is already on the TODO..

Besides that, @Chicken is correct with the statement that BlueMap will not be adding support for a specific Mod or Plugin .. 
The goal is to provide a general way for Plugins and Mods to integrate into BlueMap and or make it easy to be compatible with it, so that it, e.g. can be easily loaded as a bluemap-resourcepack..
Not sure where nova stands, and what is missing for compatibility, but before we look at that there is already a lot on the TODO towards improving mod/plugin-compatibillity :) 
So i guess I'll be working on that, and we see about Nova on the way :)
