### ISSUE TITLE
How add player icons?

### ISSUE THREAD

**Issue by MrGraversen** [BlueMap-Minecraft/BlueMap#308]
Hello! I've been using BlueMap for a while and wondered how to get player icons to show up on the map. The wiki configuration page for `plugin.conf` describes the `skinDownload` property for downloading player skins etc.

However, no player icons are showing up on my map. Any ideas?

**My Configuration Files**

**`core.conf`**
```
accept-download: true
renderThreadCount: 0
metrics: true
data: "data"
```

**`plugin.conf`**
```
liveUpdates: true
skinDownload: true
hiddenGameModes: [
  "spectator"
]
hideInvisible: true
hideSneaking: false
```

**`render.conf`**
```
webroot: "web"
useCookies: true
enableFreeFlight: true
maps: [

        {
            id: "overworld"
            name: "overworld"
            world: "/minecraft/world"
            skyColor: "#7dabff"
            ambientLight: 0.1
            worldSkyLight: 15
            removeCavesBelowY: 40
            renderEdges: true
            useCompression: true
            ignoreMissingLightData: true
        },
        {
            id: "end"
            name: "end"
            world: "minecraft/world/DIM1"
            skyColor: "#080010"
            removeCavesBelowY: -10000
            worldSkyLight: 0
            ambientLight: 0.6
        }
]
```

**Comment by TBlueF** [comment]
@MrGraversen Hi, your `world` path in your `render.conf` looks suspicious to me (one being absolute and the other one relative) .. that, or the fact that your world-location is "non-standard" might be the reason for the markers not showing up.. Since bluemap cannot identify in which world a player is then..

If you need more support, please join us on our [discord](https://discord.gg/zmkyJa3) .. GitHub Issues are not a good place for support :)
