### ISSUE TITLE
New areas are not updating in bluemap

### ISSUE THREAD

**Issue by SavageTheUnicorn** [BlueMap-Minecraft/BlueMap#312]
### What i did / Steps to reproduce
Install bluemaps
Configure
Do /bluemap start and wait until completely done
Watch bluemaps as I am In the world
Watch player marker move into unloaded chunk/black area
Check /bluemap stating render threads idle

### Expected result
Chunk loads in bluemap replacing black area as players move into them even if there is a delay.

### Actual result
No new areas were loaded and doing any of the update commands do no work.
Have 500000 chunks pregenerated with Chunky in the overworld and have not used it in the nether where i tested this issue.

### Context
**BlueMap Version:** 1.7.3 target 1.19

No

**Comment by TBlueF** [comment]
BlueMap needs to wait until the server saves the world data to disk, so it may take some time for changes to appear on the map.
The update-mechanism bluemap uses has been proven to be very reliable, if chunks are not being updated/rendered it's mostly due to one of two things:
- The server just didn't actually save the new chunks to the world-files yet *(-> use `/save-all flush` or better: restart the server and see bluemap now rendering the new area)*
- The chunks somehow have no light-data and thus are being ignored by bluemap *(unlikely in your case)*

Also make sure to click `Update Map` in BlueMap's menu to make your browser fetch a fresh copy of the updated map-tiles.

I'll close this issue as i cannot reproduce it. After making sure that minecraft saved the new chunks to the world-files, bluemap always updates them just fine on my end :)

If you have more questions about this, you are very welcome to join our [discord](https://discord.gg/zmkyJa3)!
