### ISSUE TITLE
betterend mod, blocks' texture missing

### ISSUE THREAD

**Issue by LemonPAKA** [BlueMap-Minecraft/BlueMap#317]
### What i did / Steps to reproduce
go to the_end and check blocks..

### Expected result
every blocks from betterend mod loaded fine

### Actual result
texture missing?

### Context
**BlueMap Version:**
`2.1-fabric-1.18` and also `1.7.3-fabric-1.18`

Nothing wrong in Console,other mods looks fine
logs:
[latest.log](https://github.com/BlueMap-Minecraft/BlueMap/files/9255885/latest.log)
screenshot:
![QQ截图20220804090223](https://user-images.githubusercontent.com/17202894/182741637-febff57e-fa38-4c6a-b5f5-3883a25f51f2.png)
![QQ截图20220804090309](https://user-images.githubusercontent.com/17202894/182741640-b4cc7466-1f7d-4425-b274-da8c3a1774cc.png)

**Comment by syorito-hatsuki** [comment]
For 1.7.3 try manually texture adding
https://bluemap.bluecolored.de/wiki/customization/Mods.html

**Comment by TBlueF** [comment]
BetterEnd is known to have a weird way of creating and registering their Blocks / BlockResources. BlueMap depends on the mod to have their Block-Resources in the standardized ResourcePack format in their jar. Most mods have this, better-end seems to do something else for some Blocks, which is why BlueMap can not display them correctly.

What you can do is, either
- create a ResourcePack that adds those resources for those Blocks in the "standardized" format..
or
- somehow get the authors of betterend to either change their assets to the needed format, or include extra-assets just for bluemap in their mod.jar (which i doubt they will do :D)

If you have further questions, please visit our [discord](https://discord.gg/zmkyJa3) :)
