### ISSUE TITLE
Some poi markers bug

### ISSUE THREAD

**Issue by zentixua** [BlueMap-Minecraft/BlueMap#334]
### What i did / Steps to reproduce
Create a poi marker and track its position when zooming

### Expected result
The marker will not move

### Actual result
Marker moves 50-100 blocks

### Context
**BlueMap Version:**
[Version 3.3] Purpur 1.19.2

Also:
Config file and video
[world.txt](https://github.com/BlueMap-Minecraft/BlueMap/files/9452379/world.txt)
https://www.youtube.com/watch?v=x82krT1gN0o

**Comment by TBlueF** [comment]
This is not an issue with bluemap but rather an issue with the marker-converter you used :)

Your markers are missing the `anchor` property which defines the "center" of your marker-icon ..
This defaults to the anchor for the default-icon. But since you changed your icon-image, you'll need to adjust the anchor as well :) 

*(Or adjust the converter to use the correct anchor)*

More info here: https://bluemap.bluecolored.de/wiki/customization/Markers.html#poi-markers

**Comment by girugamoz** [comment]
I was wondering about those moving icons, too. But I didn't know that it was my fault :)
I have now calculated the center of my icons and enhanced the marker-converter with a mapping from icon name to anchor definition.
Thank you @GenifeG and @TBlueF !
