### ISSUE TITLE
Server binds ip to 0

### ISSUE THREAD

**Issue by Ewtizzz** [BlueMap-Minecraft/BlueMap#336]
Cant bind my webserver to my ip
![Screenshot_20220906-105126_Chrome](https://user-images.githubusercontent.com/111651867/188578807-9d1988ff-618b-401c-8cf9-8bc41e6b0b5d.jpg)
![Screenshot_20220906-105104_Chrome](https://user-images.githubusercontent.com/111651867/188578814-da9b4b5c-fcd3-4140-91c4-0c117c44b421.jpg)

**Comment by TBlueF** [comment]
`0.0.0.0` is a placeholder for "all network interfaces" so that's perfectly fine .. if you have an issue accessing your server, then it's probably due to the port, not the ip :)

If you need support with this, please visit our [discord](https://discord.gg/zmkyJa3). GitHub Issues are the wrong place for support :)
