### ISSUE TITLE
Add example configs and their options to wiki

### ISSUE THREAD

**Issue by XCanG** [BlueMap-Minecraft/BlueMap#341]
**Is your feature request related to a problem? Please describe.**
1) I have issue where in my case `\bluemap\storages` not created on setup, so I manually add it and create empty `file.conf` because it not work without it, however I struggle to find what it should have or if it would be database, then what options it would have.

2) I have issue where caves are not properly added to my map, in wiki it not mentioned how to setup it.
In FAQ there is this that only briefly mentioned it: https://bluemap.bluecolored.de/wiki/FAQ.html#q-i-have-a-black-map--a-lot-of-the-map-is-missing
But I check every config (`core.conf`, `plugin.conf`, `webapp.conf`, `webserver.conf` (and `file.conf` is empty as I state above, so it may be here) and didn't find that option.

I only find old post on reddit that mentioned it: https://www.reddit.com/r/BlueMap/comments/pz59b9/version_163/
But I have version 3.4, but there is no `render.conf` and options seems to be different (camel-cased), so it may be moved somewhere, but wiki doesn't help with this.

**Describe the solution you'd like**

So there need a place which show for each config all available parameters to configure, because it hard to find them, I was not able to find it here in files. There a lot of different configs in `.json` or `.properties`, but there is no `.conf`s... So it need to be in wiki. For the case of bug (like 1st issue) or accidental removal (if happened).

**Comment by XCanG** [comment]
I'll add screenshot to reference cave issue:
![image](https://user-images.githubusercontent.com/4011523/191287623-f6286129-be8d-45b6-8f58-acdb05614591.png)

Tunnel is well lit, but only ceil is being rendered, not walls or floor.

Same for buildings built underground.

**Comment by TBlueF** [comment]
I think you are trying to fix the symptoms of a completely different problem: The default configs are not being generated properly.

Since everything is explained in those, the wiki doesn't need to contain this extra information. The config-templates are an essential part of bluemap. There has to be a reason why they are not being generated, so just creating them probably won't fix the issue either.

1. The storages configs get re-generated when the `storages`-folder is not present. Try deleting that and reload bluemap. Then it should generate those config-files for you. If it doesn't then there has to be an error somewhere in your logs.

2. The option to change the cave-render mechanism is the `remove-caves-below-y` setting in each map-config, those should be inside `config/bluemap/maps`. *(They are replacing the old `render.conf` from previous versions)*

This is very likely an issue with your setup and not with bluemap itself, so i will close this here on GitHub.

**Please use our very active and friendly [discord](https://discord.gg/zmkyJa3) if you need further support with this! :)**
(Or alternatively our less active [reddit](https://www.reddit.com/r/BlueMap))
