### ISSUE TITLE
Starlight support

### ISSUE THREAD

**Issue by ReeZey** [BlueMap-Minecraft/BlueMap#387]
**Is your feature request related to a problem? Please describe.**
Support for Paper's starlight generated chunks, they save lightdata more optimized, and chunks generated with starlight gets skipped cause no *vanilla* skylight data

**Describe the solution you'd like**
support starlight's skylight calculations

**Comment by pop4959** [comment]
Starlight creates vanilla compatible light data. Also, Paper already uses Starlight by default, and Bluemap works just fine, so there is no bug here.

**Comment by ReeZey** [comment]
It does create vanilla compatible BlockLight but not SkyLight data which is required otherwise they get skipped using this tool

**Comment by ReeZey** [comment]
*i'm unsure of the exact details of why this happens but from my testing chunks missing this tag gets skipped and that was just my initial thoughts of why it gets skipped

**Comment by pop4959** [comment]
Can you share where you find that it is not vanilla compatible? I have not seen examples to the contrary that it is not vanilla, nor that Bluemap doesn't render these worlds properly.

**Comment by pop4959** [comment]
> *i'm unsure of the exact details of why this happens but from my testing chunks missing this tag gets skipped and that was just my initial thoughts of why it gets skipped

It might be something else. You might want to come on the [BlueMap Discord](https://discord.gg/zmkyJa3) to do more troubleshooting before making a bug report, because it could be something else.

**Comment by TBlueF** [comment]
@ReeZey Paper is using starlight since a while now, and there have not been any problems with rendering BlueMap on paper since.
Also .. light data just "not being present" doesn't stop bluemap from rendering a chunk. It's the `Status` tag on a chunk that bluemap looks at, which is `full` once the light has been generated prorperly .. with starlight as well as with vanilla :)

Please do as pop suggested and join us on our discord to troubleshoot your problem further.

I will close this issue as this is very likely not an issue with starlight-compatibillity :)
