### ISSUE TITLE
New SQL Setup does not automatically create the database

### ISSUE THREAD

**Issue by tinyhaggis** [BlueMap-Minecraft/BlueMap#396]
I went through the guide to set up Bluemap with Forge, and used the recommended JDBC driver.  It connected to the database server but said the database didn't exist, despite having root access.  

You might want to mention in the wiki that the user needs to manually create the database, and optionally set up the unprivileged database user if it's not root.  

It could be useful if the user sets up database access with a root user that the database gets created automatically.

**Comment by TBlueF** [comment]
Since you have to explicitly specify a database in the connection-url, it's kind of implied that that database has to exist.
Giving bluemap root-access to a database is not exactly best practice either, so that's also a reason why it's implied that a database has to exist already =)

Due to this, I'd also consider it bad-practice to make bluemap create a database if it has root access, so i don't think i want to add that :)

Maybe adding a note to the wiki, or making it somehow more obvious could be considered 👍
