### ISSUE TITLE
Some areas remains black

### ISSUE THREAD

**Issue by loranger** [BlueMap-Minecraft/BlueMap#405]
Hi,

I have an issue I already encountered on few other servers, but not as important as this one.
Some areas on the map remains black, even if I force-update them

### What i did / Steps to reproduce
I created a simple creative world, opened it to few friends and after few days we decided to add a map.
I installed bluemap and triggered a `bluemap force-update world spawn_coord 5000`

### Expected result
I expected the whole area to be rendered

### Actual result
Some areas remains black, it's like a negative render of players walks.

![SCR-20230401-kogs](https://user-images.githubusercontent.com/6014/229278457-f5ba2950-3336-4a03-832c-8a8ffb8ed74f.jpeg)

I did flush tile cache and ran force-update on some small areas (`bluemap force-update world x z 50`), but they are still black.

### Context
**BlueMap Version:** 3.12
**Papermc** 1.19.4 build
No mods

**Comment by TBlueF** [comment]
This happens when you updated your world from an older minecraft-version to a newer version.
Minecraft updates the chunks that players load, those black lines are chunks that minecraft started to update but didn't finish.

You can fix this by starting the server with `--forceUpgrade` to update all chunks, and then you might need to use a plugin like https://www.spigotmc.org/resources/light-cleaner.42469/ to make sure all chunks have their light generated.

GitHub is the wrong place for support. If you need more help or info, please visit our [Discord](https://discord.gg/zmkyJa3) =)
