### ISSUE TITLE
Good old "world_nether, world_the_end folders doesnt exist"

### ISSUE THREAD

**Issue by ryslavy** [BlueMap-Minecraft/BlueMap#417]
### What i did / Steps to reproduce
I made Paper 1.19.4 server with (now) latest BlueMap-3.13-spigot.jar.. I configured core.conf and thats all

### Expected result
I expected world_nether and world_the_end being recognizable by BlueMap
![image](https://user-images.githubusercontent.com/82129251/235288204-2682b90c-8f33-48b7-84d6-e7d090ae73f3.png)
![image](https://user-images.githubusercontent.com/82129251/235288231-56dcc1d2-b882-4321-9cad-bad8ae81ff46.png)

### Actual result
![image](https://user-images.githubusercontent.com/82129251/235288119-d46467b3-e063-4cbb-9b8b-a50e587cebbe.png)

### Context
**BlueMap Version:**  
`BlueMap-3.13-spigot.jar`

**Comment by TBlueF** [comment]
You have `\\` in your config instead of `/` ... you probably copied the configs from a windows test-setup to linux ^^
Change it to `world: "world_nether/DIM-1"` and it will work.
Make sure to check all the other config files too, if they have backslashes (windows) instead of forwardslashes (linux).

Please visit our [discord](https://discord.gg/zmkyJa3) if you need more support :)
