### ISSUE TITLE
Feature request support to use Dedicated GPU from server side for calculation support.

### ISSUE THREAD

**Issue by Khan8615** [BlueMap-Minecraft/BlueMap#464]
I have dedicated machines with decent 1070ti & 1080ti gpus setup in them ( 1 for each machine )

It would be great if this mod/webserver could use the dedicated GPU to do its processor calculations instead of using the CPU cores.

**Comment by TechnicJelle** [comment]
Believe me, we pretty much all agree that this would be amazing and would indeed be much faster.
However, besides the fact that it'd be a super huge amount of work, most dedicated servers just don't have a GPU at all, so it'd be kind of useless for most BlueMap users...

**Comment by freanz3000** [comment]
"most"

**Comment by TBlueF** [comment]
@freanz3000 No need to sarcastically necro an old issue ;D

I actually disagree with Jelle's comment about it being faster, it wouldn't be.
A GPU is not simply a "faster CPU",
GPU's are made for simple but very parallel operations -> they are [SIMD](https://en.wikipedia.org/wiki/Single_instruction,_multiple_data) processors.
But BlueMap's rendering process is a huge and complex tree of conditional operations. Not at all what GPU's are made for and **exactly** what CPU's are really good at.

You can use GPU's for stuff like World-Generation since that uses mostly [noise](https://en.wikipedia.org/wiki/Perlin_noise), and generating noise is perfect for GPU's.
But BlueMap doesn't generate worlds, it generates 3D-models of worlds :D

So: this is simply not feasible and not worth it at all :)
