### ISSUE TITLE
Documentation does not mention if the port should be TCP or UDP

### ISSUE THREAD

**Issue by aaronfranke** [BlueMap-Minecraft/BlueMap#465]
### What i did / Steps to reproduce

I read these pages

https://bluemap.bluecolored.de/wiki/getting-started/Installation.html

https://bluemap.bluecolored.de/wiki/FAQ.html

### Expected result

The documentation should say if the port that needs forwarding is TCP or UDP.

### Actual result

The strings "TCP" and "UDP" do not appear once on either of the pages.

### Context

N/A, this is about the website, it's not about any specific version of BlueMap.

**Comment by TechnicJelle** [comment]
All websites on the internet are TCP. This includes BlueMap.
Other services, that aren't websites, sometimes use UDP.
Though there is nothing wrong with opening a port as both TCP and UDP.

**Comment by TBlueF** [comment]
Explaining how to open a port for a webservice is not part of bluemap's documentation. If you want to host a webservice like bluemap over your own network then you are expected to have basic knowledge on how to do this or be able to research it yourself :)

**Comment by aaronfranke** [comment]
This isn't about documenting opening ports in general, it's about documenting what BlueMap needs. I am familiar with opening ports (the same VM is hosting SSH, a web server, and a Minecraft server just fine), but BlueMap wasn't working so I was troubleshooting by reading the documentation.

(for the record, I still wasn't able to get it working even when trying both port types, so this doc improvement wouldn't have actually resolved the issue, but it would have helped narrow things down)

> or be able to research it yourself :)

To be clear: Reading the official documentation... is research.

**Comment by TBlueF** [comment]
I added it to the FAQ.

I don't want to add it to the Installation page since i think it doesn't fit there and would need a whole different section of explanation to not confuse people that are coming from a managed service.

I think most people reading those docs either don't need to know whether their servers router needs to be forwarding TCP or UDP packets on bluemap's port, or they are familiar with the fact that http webservers are commonly using the TCP protocol ^^

The few people that are wondering were usually quickly asking about it on our discord, but now they can find it in the FAQ as well :)
