### ISSUE TITLE
Suggestion: Add S3 storage support

### ISSUE THREAD

**Issue by InvalidPandaa** [BlueMap-Minecraft/BlueMap#469]
hey, it would be cool if bluemap supports s3 for render storge. Maybe you could add that?

**Comment by TBlueF** [comment]
I currently have way too little knowledge about AWS/S3 Storages to be able to do this..
And building this knowledge is a lot of work, so there has to be a bit more demand before i will consider doing this.

Closing this, since it's currently not planned and suggestions don't belong here on GitHub anyways :)

*Edit: a good PR implementing S3 would be something i would be likely to accept*
