### ISSUE TITLE
Default IP should not be 0.0.0.0 as it conflicts with server nodes.

### ISSUE THREAD

**Issue by furtabs** [BlueMap-Minecraft/BlueMap#476]
https://github.com/BlueMap-Minecraft/BlueMap/blob/7047df73d0b9aeae424943479066dde34fbb3826/BlueMapCommon/src/main/java/de/bluecolored/bluemap/common/config/WebserverConfig.java#L43

![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/48419040/d2bce213-c664-447b-aeb7-843595c21009)

**Comment by furtabs** [comment]
And it doesn't seem to be configurable anymore in the webserver.conf

**Comment by TechnicJelle** [comment]
You can bind to other IPs by manually adding a line to `webserver.conf` like this:
```hocon
ip: 127.0.0.1
```
The option is hidden, because in 99.999% of cases, it works just fine. In fact, it used to not be hidden, and we'd get dozens of people with questions about why their map wasn't working. It was because they'd assigned the wrong IP.
So the option was hidden, but not removed, to prevent people from messing it up.

**Comment by TBlueF** [comment]
What jelle said :)
