### ISSUE TITLE
Add ability to do low-resolution only maps?

### ISSUE THREAD

**Issue by marc-weber1** [BlueMap-Minecraft/BlueMap#500]
I have an ~110 GB world and the bluemap took up the entire 512 GB SSD. For the sake of both disk use and performance, can you add a config setting that turns off generation AND rendering of the hires map entirely?

**Comment by TBlueF** [comment]
There is already a setting `save-hires-layer` in the map configs which does that if you set it to `false`. It will still render the highres-models since the lowres-models are dependent on data from the hires-models but the hires-models aren't saved anymore.
-> No performance improvement but a huge disk-use improvement.

BlueMap is a 3D-Map, so the 2D-Map options are very limited right now. There are plans to improve on that end, but that not yet happened.

Also please use our [discord](https://discord.gg/zmkyJa3) for support, questions or suggestions, GitHub issues are not the right place for that. :)
