### ISSUE TITLE
Firefox Flickering issue

### ISSUE THREAD

**Issue by Sqoutv** [BlueMap-Minecraft/BlueMap#530]
### What i did / Steps to reproduce
Open 1.20 Forge latest master (4.1-17  downloaded artefact on 10. March) with Firefox

### Expected result
No Flickering

### Actual result
Complete Map Flickers

### Context
4.1-17  downloaded artefact on 10. March

Windows, Server on Forge 1.20.1
Mods were used on the map.

Also:
Problem only occurs on Firefox Browser, very similar issue: https://github.com/BlueMap-Minecraft/BlueMap/issues/522

**Comment by TBlueF** [comment]
Have you updated your webapp after upgrading from 4.1 to 4.1-17?
-> deleted the `index.html` so bluemap regenerates it?

If not, do that. And see if that fixes your issue.

**Comment by Sqoutv** [comment]
> Have you updated your webapp after upgrading from 4.1 to 4.1-17? -> deleted the `index.html` so bluemap regenerates it?
> 
> If not, do that. And see if that fixes your issue.

Yes i did, clean install of Bluemap

**Comment by TBlueF** [comment]
Then i'll need either a link to your flickering map or some more info on how to reproduce your issue as it's working fine on my end :)

**Comment by Sqoutv** [comment]
Yup sure, in my browser console this error appears constantly: 
```
Uncaught TypeError: undefined has no properties
    step http://projectserver.modded.fun:8100/assets/index-9d2e9578.js:3227
    render http://projectserver.modded.fun:8100/assets/index-9d2e9578.js:4164
    render http://projectserver.modded.fun:8100/assets/index-9d2e9578.js:4164
    MapViewer http://projectserver.modded.fun:8100/assets/index-9d2e9578.js:4164
```

Link to the map is projectserver.modded.fun:8100

**Comment by Sqoutv** [comment]
> Yup sure, in my browser console this error appears constantly:
> 
> ```
> Uncaught TypeError: undefined has no properties
>     step http://projectserver.modded.fun:8100/assets/index-9d2e9578.js:3227
>     render http://projectserver.modded.fun:8100/assets/index-9d2e9578.js:4164
>     render http://projectserver.modded.fun:8100/assets/index-9d2e9578.js:4164
>     MapViewer http://projectserver.modded.fun:8100/assets/index-9d2e9578.js:4164
> ```
> 
> Link to the map is projectserver.modded.fun:8100

Newest Firefox version btw, adblocker extension disabled

**Comment by Sqoutv** [comment]
Okay the problem just solved itself after i double clicked on a block, very weird. It has been like this for days and now that i post a issue about it it just stopped...

**Comment by TBlueF** [comment]
Yeah .. i was about to tell you that i cannot reproduce your issue, even with your link.
If it's solved for you too then perfect 👍 
Closing..

**Comment by WenHe233** [comment]
Had the same problem with chrome on windows, tried using chrome on ios as well as safari and had the same problem.
Version of bulemap used: [Version 4.1 (Snapshot)](https://github.com/BlueMap-Minecraft/BlueMap/releases/tag/v4.1)
Test link: https://mcmap.wen-he.icu/ 

Tried updating the version to BlueMap-4.1-18-forge-1.20.jar and the problem was solved!

**Comment by ASTRELION** [comment]
I'm experiencing this as well with both Firefox and LibreWolf on Windows, with a fresh install of BlueMap 5.5 on a 1.21 Paper server. It does not occur on Chromium.

Also worth noting, I experience the same issue when using https://mcmap.wen-he.icu/ as the other user used above, as well as the demo server at https://bluecolored.de/bluemap/.

It only happens when viewing the map close enough to where you can rotate it around (3D). It doesn't happen if you're zoomed out to where the map becomes 2D.

> Okay the problem just solved itself after i double clicked on a block, very weird

This seems to fix it temporarily for me as well, though it doesn't always work

**Comment by TechnicJelle** [comment]
@ASTRELION It could be that LibreWolf's extra security features are interfering with BlueMap's rendering.

Brave also has similar issues, because of such things.
Sometimes it just doesn't show any menu buttons at all.
Or the camera jumps up and down wildly.
(That happens because Brave adds some noise when reading out image data, "for security reasons", but BlueMap uses that function to read height data, to base the camera position on!)

Could you see if this issue also happens on normal Firefox? Or maybe you can disable some security features on BlueMap for a moment to see if that fixes it?

**Comment by ASTRELION** [comment]
> Could you see if this issue also happens on normal Firefox

It does, I tried with a virtually fresh install of plain Firefox and I get the same problems. Interestingly, Firefox Developer Edition does not have the issue; it also does not happen on Firefox for android.

I installed Brave just to test it out, and it's actually much better than Firefox. Though, it does jitter a bit sometimes when moving around and doesn't seem to get the height correctly as you mentioned.

> That happens because Brave adds some noise when reading out image data

That's interesting, I didn't know that!

Edit:
I installed Firefox and Firefox Developer Edition on another Windows computer, and both seem to work flawlessly. LibreWolf still does not. So I'm not sure what's going on with my main system with Firefox. On my main system I uninstalled and reinstalled Firefox to be sure and it still has the issue.

**Comment by TechnicJelle** [comment]
(Personal opinion: I do not actually recommend using Brave for anything, really. [Explanation](https://www.spacebar.news/stop-using-brave-browser/)
If I need a chromium-based browser for something, I personally just stick to (ungoogled) chromium itself.
I just mentioned Brave because it has similar issues.)

Could you try using the devtools performance analyser?

**Comment by ASTRELION** [comment]
> I do not actually recommend using Brave for anything, really

Yeah, I don't for basically the same reasons you linked :). I use LibreWolf as my daily driver so it would be nice if BlueMaps would work on it, but I'd understand if there's too high a development cost there since not many people use it. (Though it just doesn't work on regular Firefox for me, so I'm not sure how relevant LibreWolf actually is or not here)

> Could you try using the devtools performance analyser

I haven't used the performance tools much before so I don't know how much help I'd be. I recorded while the screen was jittering crazily from 0s-24s while zoomed in, 24-33s was when I zoomed out and it became stable, and 34s on was zoomed in again. https://share.firefox.dev/3ZHNTM0
