### ISSUE TITLE
Add a set for developers that holds other marker sets

### ISSUE THREAD

**Issue by BrailleBennett** [BlueMap-Minecraft/BlueMap#544]
This idea suggests implementing a set that holds different individual marker sets, called a super set in this post.
A super set would allow developers who may have many different sets of markers in their addon to add them to different sets without fear of flooding the marker set list. My ideal implementation of this would let players toggle either the entire super set on or off at once, or expand the list and enable/disable certain sets within the super set. For example, if each entity type in the game was marked on its own set, it would be many many sets for the list to display, and could very easily hide other sets because players don't want to scroll down. If a super set was used, it would make it so a player could either just quickly check/uncheck the super set, or expand it to see every subset in closed in it. I propose that this should be added only to the API for developers to utilize in their plugins for now, as the current set system is confusing enough for the average server owner.

**Comment by TBlueF** [comment]
Nested marker-sets are not that hard to implement actually, the webapp **almost** supports it already, it would need some smaller changes in the API and server-side implementation.
It will likely happen at some point, i definitely want to go into that direction. It might require a breaking API change, so that would be the only problem if it does...

Closing this ticket tho, as suggestions should go into the corresponding discord channel instead of a github issue :)
(See [Contribution Guidelines](https://github.com/BlueMap-Minecraft/BlueMap/blob/a6402850c90e0547d1bdd686ad085a69c6c47137/.github/CONTRIBUTING.md#suggesting-a-new-feature-or-change))
