### ISSUE TITLE
[CLI] Only one world is checked for if it is done

### ISSUE THREAD

**Issue by Katrix** [BlueMap-Minecraft/BlueMap#8]
Using the CLI to generate a map for a bunch of worlds. 

## Steps taken

1. Rendered a rather small world.
2. Restarted the CLI once it was done. (It had started on the next world)
3. CLI informs me that the first map is done, and that nothing needs to be done.
4. At this point the CLI does not start rendering the next map.

If the map that was done rendering is commented out, it moves on to the next one.

**Comment by TBlueF** [comment]
So, how did you start the CLI (command)? Because the only way to start it "on a world" is to change the configuration or another configuration-folder with another configuration as a start parameter.

Usually you would configure all your worlds/maps in one config and then run the CLI once on that config and it will generate all defined worlds/maps sequentially.

**Comment by TBlueF** [comment]
Ah i see, i found the issue.
Thanks, i will fix that soon.
